name: build_by_api
run-name: Build by API from user @${{ github.actor }}

on: 
  repository_dispatch:
    types: [api-build]

jobs:
  build:
    name: Build Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Run Unit Tests
        run: mvn clean test

      - name: Build with Maven
        run: mvn -DskipTests -B package --no-transfer-progress --file ./pom.xml

      - name: rename Artifact
        run: mv ./target/*digitalbank*.jar "./target/${{ github.event.client_payload.artifactName }}.jar"

      - uses: actions/upload-artifact@master
        with:
          name: ${{ github.event.client_payload.artifactName }}.jar
          path: ./target/*.jar
